### ISSUE TITLE
functionalitate "Devino Facilitator"

### ISSUE THREAD

**Issue by SergiuB** [SergiuB/harmonia-astro#3]
Am adaugat buton pe Home page (sub "vezi toti facilitatorii") si in meniu, unde am inlocuit "Devino membru" - **dar daca nu avem inca mecanism de membership eu zic sa nu mai afisam butonul asta, decat sa te duca pe o pagina work in progress.**

Acum ca vad cum arata, poate butonul de "devino facilitator" pus pe home page ar putea fi scos totusi, pe ideea ca "devino facilitator" va fi o functionalitate rar folosita, prin comparatie cu "vezi toti facilitatorii" si poate **nu are sens sa il aratam mereu tuturor pe home page? Ce ziceti**? As lasa devino facilitator doar in meniu, eventual si in meniul din footer (jos de tot).

"Devino facilitator" duce la o pagina unde am embed-uit un Google form. Acest google form deocamdata pe pt contul meu personal de Google si **trebuie inlocuit cu un form creat pe contul Google al Harmonia**. Raspunsurile completate vor fi puse intr-un spreadsheet Google.

@tibibozi fa tu te rog form-ul similar cu asta, dar pe contul Harmonia: https://docs.google.com/forms/d/1rhsPrbwFUfXWOS-R0zBaMvL3Vpk9AKrbivJpP1dEB3c/edit

Cand il ai dai Send si alegi Embed:
![image](https://github.com/SergiuB/harmonia-astro/assets/3169325/0d9c7b14-216e-453a-b97c-22c8bf95e9f9)

Faci Copy la textul "<iframe src...>" si imi trimiti, sa inlocuiesc formul meu cu al tau. Pe urma poti modifica cuum vrei formul, se va reflecta in site.

**Comment by tibibozi** [comment]
Salutare, Sergiu. 
Da, legat de butoanul "Devino Facilitator" il vom pune in Meniuul de sus  si in Meniul de jos din Footer. 
Si da, renuntam la butonul " Devino Membru " momentan. 

Mai jos ai formul de pe contul harmonia. Sper ca am procedat corect.

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeduo18a8PHoO3m1YIotjLdtbHBBkvrdmXyQFxNt-JXzmRlJw/viewform">

**Comment by SergiuB** [comment]
@tibibozi e in regula, doar mai trebuie sa schimbi un pic culoarea de accent la form.
1. deschide editorul in care ai creat formul
2. in meniul dreapta sus ai un icon button cu o paleta de culori
3. la Color apasa butonul + sa adaugi o culoare noua
4. introdu culoarea noua cu valoarea hex: #224884 si apasa add.
