### ISSUE TITLE
functionalitate: Pagina facilitatorului

### ISSUE THREAD

**Issue by SergiuB** [SergiuB/harmonia-astro#7]
Datele pentru un facilitator nou se adauga in https://github.com/SergiuB/harmonia-astro/tree/main/src/content/facilitators

1. Se creeaza un fisier `[nume].md` (vezi alex.md ca exemplu)
2. Pentru poze se creeaza un director in `src/content/facilitators/[nume]` unde se uploadeaza pozele.

**Comment by SergiuB** [comment]
Asa se creeaza/adauga fisiere noi ![image](https://github.com/SergiuB/harmonia-astro/assets/3169325/1a4d41a9-0432-4ddd-b181-76cf12d914a9)

**Comment by tibibozi** [comment]
Salutare, Sergiu! 

Felicitari pentru ce ai construit, se vede marfa pana acum. 

Am sa las mai jos ce observ ca este necesar a fi  imbunatatit/ editat/ adaugat in pagina personala de facilitator: 

-  Cred ca merg facute **Cuvintele cheie** ale Facilitatorului **ceva mai mici** pentru a incape inca unul dedesupt si pentru a se vede estetic. De ex la Alex Ionescu, sub numele lui avem: "Acupunctura" "Medicina Chineza" si ar fi nice sa mai incapa inca unul " Terapeut Maseur" . Practic **sa oferim oportunitatea de a alege intre 1 si 3 Cuvinte Cheie care sa-l definesca pe Facilitator**. In rest e foarte fain cum se vede.

- la Servicii va fi necesar sa urmarim cum a facut mihai la design pe figma ( [https://www.figma.com/file/pNGm1URNnwSi9gtsxMZ3lo/Harmonia-webS-Mobile?node-id=0%3A1&mode=dev](url) ) Deci, vor fi necesare urmatoarele modificari: 1. Sa avem "Servicii individuale" si "Servicii de grup"  care astea sa se deschida ficare atunci cand dai click. 
Ex la Tiberiu Bozi: o sa avem in loc de "Servicii" sa fie direct "**Servicii individuale**" si "**Servicii de grup**". Iar atunci cand deschizi una dintre ele, sa zicem ca deschidem "Servicii individuale =>apoi se deschid serviciile ( **Emotion somatic release, Harmonic reborn**, etc). Cand dam click pe una dintre ele vom avea asa:  **(E)motion Somatic Release (scurta descriere cu Pret, Durata + Buton cu "Citeste mai mult"**   care sa te duca catre => **Descrierea serviciului + o poza (optional)+  Contacteaza facilitatorul pentru a face o rezervare**. Si chiar langa sa fie un **buton cu "REZERVA"** care sa duca catre **un link de whatsapp cu nr de telefon al facilitatorului**. (Cred ca asa e cel mai simplu mod de a arata estetic bine si de a nu mai implementa un intreg sistem in care lumea sa-si faca rezervare direct pe website  care e mai complicat in al gestiona) . 
- La Locatie, consider ca nu este necesar sa punem harta google si la facilitatori pentru ca nu toata lumea va avea locatie google. Cel mai bine e sa ramanem la a doua optiune. Cea in care pui **text+ link** cu Numele si nr adresei. Plus ca ocupa mai putin spatiu 
- Un alt lucru care e necesar a fi adaugat va fi pe langa Descriere, Servicii, Locatie si **Contact**. Sub Contact sa-ti puna lumea **mail, nr telefon , cu pagina de instagram sau facebook si website.** 
- Ultimul aspect care-mi vine in minte.. ar fi ideal sa facem cumva ca eu sau facilitatorul sa putem completa datele ( Pagina principala + descrieri + servicii etc)  intr-un mod super simplu ca sa nu fie necesar sa completam cu COD pentru fiecare facilitator in parte.. adica eu ma pierd in ele si imi cam mananca destul timp. In acest moment, daca vreau sa ma pun acum pe mine si pe altii, cum fac? Creez acel fisier [tiberiubozi.md] si bag textul in acel cod? Crezi ca putem avea pe viitor o solutie ca sa simplificam completarea datelor pentru Users? sau pentru mine macar? Adica nu ma deranjeaza sa pun doar textul si pozele in [tiberiubozi.md] .. dar ma gandesc ca nici pentru tine nu ar fi chiar ideal  sa faci CODul la fiecare facilitator.  hm hm hm. O sa fac un test cu mine prima data sa vedem ce iese, dar dupa ce sunt bifate si modificarile de mai sus. 

**Multumesc, draga Sergiu! <3 
Mult spor!**

**Comment by SergiuB** [comment]
> la Servicii va fi necesar sa urmarim cum a facut mihai la design pe figma ( [https://www.figma.com/file/pNGm1URNnwSi9gtsxMZ3lo/Harmonia-webS-Mobile?node-id=0%3A1&mode=dev](https://github.com/SergiuB/harmonia-astro/issues/url) ) Deci, vor fi necesare urmatoarele modificari: 1. Sa avem "Servicii individuale" si "Servicii de grup" care astea sa se deschida ficare atunci cand dai click.

Credeam ca separarea asta de servicii apare doar la Activitati, asa e designul lui Mihai. 
Esti sigur ca la fiecare terapeut vrei sa apara acest pas, de a expanda "servicii individuale" si "servicii de grup"? Dacaa majoritatea facilitatorilor nu ofera decat servicii iindividuale?

Ca sa afie cat mai simplu pentru utilizator as propune asa:
1. Daca facilitatorul ofera doar servici individuale, atunci nu mai facem nici o sepaaratie, le listam asa.
2. Daca facilitatorul ofera si grup si individual, atunci separam, dar afisam "individual" si "de grup" deja expandate, ca sa il scutim de un click in a vedea serviciile.

Gen asa:

### Servicii individuale
 - X - dai click si se expandeaza la scurta descriere cu Pret, Durata + Buton cu "Citeste mai mult" care sa te duca catre => Descrierea serviciului + o poza (optional)+ Contacteaza facilitatorul pentru a face o rezervare
 - Y
### Servicii de grup
- Z

**Comment by tibibozi** [comment]
Bun. De acord! Așa vom face 🫱🏼‍🫲🏻

**Comment by SergiuB** [comment]
@tibibozi vezi https://66139897dd2b2600083daa58--harmoniaworld.netlify.app/facilitators/alex/ (este un permalink la o versiune fixa a siteului. Aceste permalinkuri ne ajuta sa vedem cum era siteul la fiecare schimbare din trecut)

1.
> Cred ca merg facute Cuvintele cheie ale Facilitatorului ceva mai mici pentru a incape inca unul dedesupt si pentru a se vede estetic
  
Done

2. Am simplificat cat am putut de mult modul in care se introduc datele facilitatorului. Aceasta se face tot prin [fisierul Markdown corespunzator fiecarui facilitator](https://github.com/SergiuB/harmonia-astro/blob/main/src/content/facilitators/alex.md?plain=1). Acest fisier are  doua parti:
   - o parte numita **frontmatter** aflata intre liniile "---", unde se completeaza datele fiecarui facilitator. 
   - o parte **content** (dupa al doilea "---") unde vine descrierea facilitatorului. 
Sper ca e ok. Mai simplu de atat ar fi sa cream un form in care se introduc datele, dar e mult mai mult de munca.

3. Deocamdata nu poti vedea detaliile unui serviciu, dar urmeaza ca fiecare serviciu din lista sa fie clickabil si expandeaza detaliile, cu descrierea completa, eventual poze, si buton de rezervare.

4. Am pus datele de locatie si contact, dar sunt doar unele sub altele, fara un design anume pentru ca nu am. Asgtept sugestii aici.

**Comment by tibibozi** [comment]
@SergiuB bun, bun. Vin aici cu urmatoarele:

2. legat de fisierul markdown, e marfa si pare usor.  o sa ma pun pe mine ca facilitator, sa vedem cum iese. 
3.  Legat de Servicii, 
- cred  ca putem sa lasam precum am spus astazi. Si anume doar **Servicii** ( sa nu mai delimitam serviciile individuale cu cele de grup. 
- tot aici, ca sa delimitam frumos fiecare serviciu in parte, **hai sa le incardam intr-un dreptunghi** pe fiecare dintre ele.  EX: Vezi website-ul meu actual [https://www.harmoniaoptima.com/terapii](url) (dar vezi mai bine direct de pe mobil ca pe web se vede diferit)
4. Cat despre contact, e fain asta cu linkurile. Hai sa punem scrisul de la stanga si i-am scris in WORD lui Mihai sa ne trimita ceva design cu: adresa, nr tel, mail, website, fb, insta . Dar pana trimite Mihai ceva, hai sa punem scrisul direct. EX: "Adresa: Str. Avrig 63" "Telefon: 0734693145" "Mail: bozitiberiu@gmail.com" "Website: harmoniaoptima.com"

GG Sergiu

**Comment by SergiuB** [comment]
@tibibozi verifica te rog https://harmoniaworld.netlify.app/facilitators/alex/ si vezi daca mai e ceva de facut la servicii.
 - daca dai click pe un serviciu se expandeaza cu descriere si imagine
 - butonul "REZERVA" te duce la [link-ul definit pentru a face rezervare](https://github.com/SergiuB/harmonia-astro/blob/80e68f5e988b561d1c70c7a366d3753a0f0111da/src/content/facilitators/alex.md?plain=1#L28), care poate fi un link de Whatsapp sau un link catre un calendar extern gen Calendly saau GoodTime.

**Comment by tibibozi** [comment]
Wow! Sergiu, am apucat sa ma uit. Am doar laude pentru tine si pentru ce ai facut. BRAVO! I'm proud. Imi place super mult cum arata. In acest moment nu vad ce as mai putea adauga/scoate/modifica. Doar vom inlocui cuvinte din Contact cu iconite, atunci cand Florin le trimite. Arata foarte faina aceasta expandare a serviciilor si pozele care sunt inital ALB-Negru, iar apoi cand dai click pe ele se fac Color. Big UP!

**Comment by tibibozi** [comment]
sergiu. sunt n00b. cum fac un director nou in images? nu mai gasesc..  

Edit: am rezolvat

**Comment by tibibozi** [comment]
Te salut, Sergiu. Cum merge? 

Am inceput sa urc facilitatori pe website. Intampin o **eroare la DeliaFlorea.md** . Am incercat sa o identific, dar nu am gasit ce se intampla. Pe website observ ca nu apar toate terapiile, deci ma gandesc ca ar fi o problema mica pe undeva, dar nu o sesizez. Creezi ca ma poti ajuta cu asta?  Multumesc.

De atlfel, te ajuta daca la fiecare facilitator iti scriu aici ce fel de activitati are? 

pentru **Delia avem urmatoarele Activitati pentru sesiuni individuale:**
1. Scanare Zyto
2. Masaj
3. Aromaterapie
4. Alte sesiuni
5. Access Bars
![eroare](https://github.com/SergiuB/harmonia-astro/assets/164945303/1d1b2b74-ee38-4142-ba78-b154548e0a7e)

**Comment by tibibozi** [comment]
Un alt lucru issue pe care-l am acum este la Hostiuc Paul.md . Am inceput sa-I creez profilul de facilitator, am dat safe sa vad cum se arata pe website și nu apare. Oare de ce? 

Multumesc, draga Sergiu!

**Comment by tibibozi** [comment]
salutare, Sergiu. Am facut ceva update la Paulhostiuc.md, i-am adaugat ceva mai multe servicii  si nu mai face update pe website. Ai idee de ce? si la mine am modicat ceva la unul din servicii si la fel, nu da update.  

Diseara o sa mai completez la Paul ca are peste 30 de servicii si voiam sa ma asigur ca e totul ok si sa nu muncesc degeaba.

**Comment by SergiuB** [comment]
De muncit nu muncesti degeaba, baga acolo si o sa  ma uit, nu se pierde nimic. Probabil iar niste ghilimele in plus.


Sent from Yahoo Mail for iPhone


On Thursday, April 25, 2024, 2:17 PM, tibibozi ***@***.***> wrote:




salutare, Sergiu. Am facut ceva update la Paulhostiuc.md, i-am adaugat ceva mai multe servicii si nu mai face update pe website. Ai idee de ce? si la mine am modicat ceva la unul din servicii si la fel, nu da update.

Diseara o sa mai completez la Paul ca are peste 30 de servicii si voiam sa ma asigur ca e totul ok si sa nu muncesc degeaba.

**Comment by SergiuB** [comment]
@tibibozi am rezolvat problema la paul, lipseau niste "]" in incheiera campului "description" la servicii. Probabil in viitor ar trebui sa facem introducerea serviciilor printr-un formular google, astfel incat sa fie eliminate astfel de greseli, dar intai sa facem V1 pentru site.
